---
- name: Deploy Apache and FTP containers
  hosts: 172.20.10.3
  become: yes
  tasks:
    - name: configure a network for Apache container
      docker_network:
        name: apache_network
        state: present
        driver: bridge
        ipam_config:
           - subnet: 192.168.10.0/24

    - name: configure a network for FTP container
      docker_network:
        name: FTP_network
        state: present
        driver: bridge
        ipam_config:
           - subnet: 192.168.20.0/24

    - name: Start Apache container
      docker_container:
        name: apache_container
        image: mukundatit/httpd
        state: started
        ports:
          - "8080:80"
        networks:
          - name: apache_network
          - name: FTP_network  # Connect to both networks
        restart_policy: always

    - name: Pull FTP container image
      docker_image:
        name: stilliard/pure-ftpd
        source: pull
        state: present

    - name: Create an FTP container
      docker_container:
        name: ftp_container
        image: stilliard/pure-ftpd
        state: started
        ports:
          - "21:21"
        networks:
          - name: FTP_network
          - name: apache_network  # Connect to both networks
        volumes:
          - /home/mukund/Downloads:/home/ftpuser
        env:
          FTP_USER_NAME: ftpuser
          FTP_USER_PASS: ftp_password
          FTP_USER_HOME: /home/ftpuser
        restart_policy: always
